CREATE TABLE EMPLEADOS(
    DNI CHAR(9) PRIMARY KEY NOT NULL,
    Nombre VARCHAR2(40),
    Localidad VARCHAR2(40),
    COD_Sucursal INT
);
CREATE TABLE SUCURSALES(
    COD_Sucursal INT,
    Direccion VARCHAR2(40),
    Localidad VARCHAR2(40)
);

ALTER TABLE EMPLEADOS ADD(
    CONSTRAINT FK_EMP FOREIGN KEY (COD_Sucursal) REFERENCES SUCURSALES(COD_Sucursal)
);
