/*Ejercicio 1*/
SELECT nomem 
FROM EMPLEADOS
WHERE salar > ALL(SELECT salar FROM EMPLEADOS WHERE numde=122)
ORDER BY 1 ASC;

/*Ejercicio 2*/
SELECT nomem
FROM EMPLEADOS
WHERE salar > ALL(SELECT salar FROM EMPLEADOS WHERE numde=150)
ORDER BY 1 ASC;

/*Ejercicio 3*/
SELECT nomem
FROM EMPLEADOS
WHERE salar > SOME(SELECT 2.5*salar FROM EMPLEADOS WHERE numde=122)
ORDER BY 1 ASC;

/*Ejercicio 4*/
SELECT nomem, salar 
FROM EMPLEADOS 
WHERE salar = SOME(SELECT 10*comis FROM EMPLEADOS)
ORDER BY 1 ASC;

/*Ejercicio 5*/
SELECT nomem, salar
FROM EMPLEADOS
WHERE salar > ALL(SELECT comis*20 FROM EMPLEADOS WHERE comis IS NOT NULL)
ORDER BY 1 ASC;

/*Ejercicio 6*/
SELECT nomem, salar
FROM EMPLEADOS
WHERE salar< ALL(SELECT comis*20 FROM EMPLEADOS WHERE comis IS NOT NULL)
ORDER BY 1 ASC; 